In [1]:
#pandasi import et

In [3]:
import pandas as pd

In [4]:
# datani import et

In [69]:
data = pd.read_csv("n_movies.csv")
data

,title,year,certificate,duration,genre,rating,description,stars,votes
0,Cobra Kai,(2018– ),TV-14,30 min,"Action, Comedy, Drama",8.5,Decades after their 1984 All Valley Karate Tou...,"['Ralph Macchio, ', 'William Zabka, ', 'Courtn...","177,031"
1,The Crown,(2016– ),TV-MA,58 min,"Biography, Drama, History",8.7,Follows the political rivalries and romance of...,"['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...","199,885"
2,Better Call Saul,(2015–2022),TV-MA,46 min,"Crime, Drama",8.9,The trials and tribulations of criminal lawyer...,"['Bob Odenkirk, ', 'Rhea Seehorn, ', 'Jonathan...","501,384"
3,Devil in Ohio,(2022),TV-MA,356 min,"Drama, Horror, Mystery",5.9,When a psychiatrist shelters a mysterious cult...,"['Emily Deschanel, ', 'Sam Jaeger, ', 'Gerardo...","9,773"
4,Cyberpunk: Edgerunners,(2022– ),TV-MA,24 min,"Animation, Action, Adventure",8.6,A Street Kid trying to survive in a technology...,"['Zach Aguilar, ', 'Kenichiro Ohashi, ', 'Emi ...","15,413"
...,...,...,...,...,...,...,...,...,...
9952,The Imperfects,(2022– ),TV-MA,45 min,"Action, Adventure, Drama",6.3,After an experimental gene therapy turns them ...,"['Morgan Taylor Campbell, ', 'Italia Ricci, ',...","3,130"
9953,The Walking Dead,(2010–2022),TV-MA,44 min,"Drama, Horror, Thriller",8.1,Sheriff Deputy Rick Grimes wakes up from a com...,"['Andrew Lincoln, ', 'Norman Reedus, ', 'Melis...","970,067"
9954,The Crown,(2016– ),TV-MA,58 min,"Biography, Drama, History",8.7,Follows the political rivalries and romance of...,"['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...","199,898"
9955,Supernatural,(2005–2020),TV-14,44 min,"Drama, Fantasy, Horror",8.4,Two brothers follow their father's footsteps a...,"['Jared Padalecki, ', 'Jensen Ackles, ', 'Jim ...","439,601"
9956,Devil in Ohio,(2022),TV-MA,356 min,"Drama, Horror, Mystery",5.9,When a psychiatrist shelters a mysterious cult...,"['Emily Deschanel, ', 'Sam Jaeger, ', 'Gerardo...","9,786"

In [10]:
# head,tail, descirbe, info, melumatlarina bax

In [13]:
data.head()

,title,year,certificate,duration,genre,rating,description,stars,votes
0,Cobra Kai,(2018– ),TV-14,30 min,"Action, Comedy, Drama",8.5,Decades after their 1984 All Valley Karate Tou...,"['Ralph Macchio, ', 'William Zabka, ', 'Courtn...","177,031"
1,The Crown,(2016– ),TV-MA,58 min,"Biography, Drama, History",8.7,Follows the political rivalries and romance of...,"['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...","199,885"
2,Better Call Saul,(2015–2022),TV-MA,46 min,"Crime, Drama",8.9,The trials and tribulations of criminal lawyer...,"['Bob Odenkirk, ', 'Rhea Seehorn, ', 'Jonathan...","501,384"
3,Devil in Ohio,(2022),TV-MA,356 min,"Drama, Horror, Mystery",5.9,When a psychiatrist shelters a mysterious cult...,"['Emily Deschanel, ', 'Sam Jaeger, ', 'Gerardo...","9,773"
4,Cyberpunk: Edgerunners,(2022– ),TV-MA,24 min,"Animation, Action, Adventure",8.6,A Street Kid trying to survive in a technology...,"['Zach Aguilar, ', 'Kenichiro Ohashi, ', 'Emi ...","15,413"

In [14]:
data.tail()

,title,year,certificate,duration,genre,rating,description,stars,votes
9952,The Imperfects,(2022– ),TV-MA,45 min,"Action, Adventure, Drama",6.3,After an experimental gene therapy turns them ...,"['Morgan Taylor Campbell, ', 'Italia Ricci, ',...","3,130"
9953,The Walking Dead,(2010–2022),TV-MA,44 min,"Drama, Horror, Thriller",8.1,Sheriff Deputy Rick Grimes wakes up from a com...,"['Andrew Lincoln, ', 'Norman Reedus, ', 'Melis...","970,067"
9954,The Crown,(2016– ),TV-MA,58 min,"Biography, Drama, History",8.7,Follows the political rivalries and romance of...,"['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...","199,898"
9955,Supernatural,(2005–2020),TV-14,44 min,"Drama, Fantasy, Horror",8.4,Two brothers follow their father's footsteps a...,"['Jared Padalecki, ', 'Jensen Ackles, ', 'Jim ...","439,601"
9956,Devil in Ohio,(2022),TV-MA,356 min,"Drama, Horror, Mystery",5.9,When a psychiatrist shelters a mysterious cult...,"['Emily Deschanel, ', 'Sam Jaeger, ', 'Gerardo...","9,786"

In [26]:
data.describe()

            rating
count  8784.000000
mean      6.764515
std       1.214840
min       1.700000
25%       6.100000
50%       6.900000
75%       7.600000
max       9.900000

In [25]:
data.describe().T

         count      mean      std  min  25%  50%  75%  max
rating  8784.0  6.764515  1.21484  1.7  6.1  6.9  7.6  9.9

In [16]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9957 entries, 0 to 9956
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   title        9957 non-null   object
 1   year         9430 non-null   object
 2   certificate  6504 non-null   object
 3   duration     7921 non-null   object
 4   genre        9884 non-null   object
 5   rating       8784 non-null   float64
 6   description  9957 non-null   object
 7   stars        9957 non-null   object
 8   votes        8784 non-null   object
dtypes: float64(1), object(8)
memory usage: 700.2+ KB

In [4]:
# raitingi 6.5 den boyuk olub voiting 5000+ olan row`lari goster

In [ ]:
data[(data.Customer_Age>30)&
    (data.Gender=='F')&
     ((data.Education_Level=='Graduate')|(data.Education_Level=='High School'))]

In [41]:
data['votes'] = data['votes'].str.replace(',', '')
data['votes'] = pd.to_numeric(data['votes'])
check = data[(data.rating>6.5)&(data.votes>5000)]

In [42]:
check

,title,year,certificate,duration,genre,rating,description,stars,votes
0,Cobra Kai,(2018– ),TV-14,30 min,"Action, Comedy, Drama",8.5,Decades after their 1984 All Valley Karate Tou...,"['Ralph Macchio, ', 'William Zabka, ', 'Courtn...",177031.0
1,The Crown,(2016– ),TV-MA,58 min,"Biography, Drama, History",8.7,Follows the political rivalries and romance of...,"['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...",199885.0
2,Better Call Saul,(2015–2022),TV-MA,46 min,"Crime, Drama",8.9,The trials and tribulations of criminal lawyer...,"['Bob Odenkirk, ', 'Rhea Seehorn, ', 'Jonathan...",501384.0
4,Cyberpunk: Edgerunners,(2022– ),TV-MA,24 min,"Animation, Action, Adventure",8.6,A Street Kid trying to survive in a technology...,"['Zach Aguilar, ', 'Kenichiro Ohashi, ', 'Emi ...",15413.0
5,The Sandman,(2022– ),TV-MA,45 min,"Drama, Fantasy, Horror",7.8,Upon escaping after decades of imprisonment by...,"['Tom Sturridge, ', 'Boyd Holbrook, ', 'Patton...",116358.0
...,...,...,...,...,...,...,...,...,...
9950,American Horror Story,(2011– ),TV-MA,60 min,"Drama, Horror, Sci-Fi",8.0,An anthology series centering on different cha...,"['Lady Gaga, ', 'Kathy Bates, ', 'Angela Basse...",312974.0
9951,Breaking Bad,(2008–2013),TV-MA,49 min,"Crime, Drama, Thriller",9.5,A high school chemistry teacher diagnosed with...,"['Bryan Cranston, ', 'Aaron Paul, ', 'Anna Gun...",1831359.0
9953,The Walking Dead,(2010–2022),TV-MA,44 min,"Drama, Horror, Thriller",8.1,Sheriff Deputy Rick Grimes wakes up from a com...,"['Andrew Lincoln, ', 'Norman Reedus, ', 'Melis...",970067.0
9954,The Crown,(2016– ),TV-MA,58 min,"Biography, Drama, History",8.7,Follows the political rivalries and romance of...,"['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...",199898.0
9955,Supernatural,(2005–2020),TV-14,44 min,"Drama, Fantasy, Horror",8.4,Two brothers follow their father's footsteps a...,"['Jared Padalecki, ', 'Jensen Ackles, ', 'Jim ...",439601.0

In [33]:
# certificate column da nece ferqli input var? 
# her birinin sayisi nedir/

In [32]:
data.certificate.value_counts()

TV-MA        2520
TV-14        1209
TV-PG         543
R             472
Not Rated     467
TV-Y7         349
PG-13         282
TV-Y          175
PG            159
TV-G          151
Unrated        63
G              43
TV-Y7-FV       31
Approved       26
Passed          6
NC-17           4
MA-17           1
12              1
M               1
E10+            1
Name: certificate, dtype: int64

In [43]:
# duration column u integere cevir
data.head()

,title,year,certificate,duration,genre,rating,description,stars,votes
0,Cobra Kai,(2018– ),TV-14,30 min,"Action, Comedy, Drama",8.5,Decades after their 1984 All Valley Karate Tou...,"['Ralph Macchio, ', 'William Zabka, ', 'Courtn...",177031.0
1,The Crown,(2016– ),TV-MA,58 min,"Biography, Drama, History",8.7,Follows the political rivalries and romance of...,"['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...",199885.0
2,Better Call Saul,(2015–2022),TV-MA,46 min,"Crime, Drama",8.9,The trials and tribulations of criminal lawyer...,"['Bob Odenkirk, ', 'Rhea Seehorn, ', 'Jonathan...",501384.0
3,Devil in Ohio,(2022),TV-MA,356 min,"Drama, Horror, Mystery",5.9,When a psychiatrist shelters a mysterious cult...,"['Emily Deschanel, ', 'Sam Jaeger, ', 'Gerardo...",9773.0
4,Cyberpunk: Edgerunners,(2022– ),TV-MA,24 min,"Animation, Action, Adventure",8.6,A Street Kid trying to survive in a technology...,"['Zach Aguilar, ', 'Kenichiro Ohashi, ', 'Emi ...",15413.0

In [48]:
data['duration'] = data['duration'].str.replace(" min","")
data['duration']=pd.to_numeric(data['duration'])
print(data['duration'].dtype)

float64

In [ ]:
# certificate kolununa gore ortalama duration goster
# elde etdiyin melumati orginal dataya join et

In [71]:
data['duration'] = data['duration'].str.replace(" min","")
gr_data = data.groupby(['duration'],as_index=False)[['duration']]\
                .mean().rename(columns={"duration":"duration_avg"})

In [72]:
gr_data

      duration_avg
0     6.944444e+13
1     9.182736e+19
2              inf
3    1.148876e+261
4    1.418085e+213
..             ...
286  9.324009e+205
287  9.421134e+205
288  1.137815e+172
289  1.162791e+170
290   9.900000e+02

[291 rows x 1 columns]

In [74]:
data['duration'] = data['duration'].astype(float)
merged_data = pd.merge(data, gr_data, left_on='duration', right_on='duration_avg', how='left')
merged_data.head()

,title,year,certificate,duration,genre,rating,description,stars,votes,duration_avg
0,Cobra Kai,(2018– ),TV-14,30.0,"Action, Comedy, Drama",8.5,Decades after their 1984 All Valley Karate Tou...,"['Ralph Macchio, ', 'William Zabka, ', 'Courtn...","177,031",NaN
1,The Crown,(2016– ),TV-MA,58.0,"Biography, Drama, History",8.7,Follows the political rivalries and romance of...,"['Claire Foy, ', 'Olivia Colman, ', 'Imelda St...","199,885",NaN
2,Better Call Saul,(2015–2022),TV-MA,46.0,"Crime, Drama",8.9,The trials and tribulations of criminal lawyer...,"['Bob Odenkirk, ', 'Rhea Seehorn, ', 'Jonathan...","501,384",NaN
3,Devil in Ohio,(2022),TV-MA,356.0,"Drama, Horror, Mystery",5.9,When a psychiatrist shelters a mysterious cult...,"['Emily Deschanel, ', 'Sam Jaeger, ', 'Gerardo...","9,773",NaN
4,Cyberpunk: Edgerunners,(2022– ),TV-MA,24.0,"Animation, Action, Adventure",8.6,A Street Kid trying to survive in a technology...,"['Zach Aguilar, ', 'Kenichiro Ohashi, ', 'Emi ...","15,413",NaN

In [ ]:
# Genresi Drama olan durations 30+ olan ratingi 5+ olan voitingi ise 100k ve 200k arasi olan rowlari goster

In [62]:
data['duration'] = data['duration'].str.replace(" min","")
data['duration']=pd.to_numeric(data['duration'])
data['votes'] = data['votes'].str.replace(',', '')
data['votes']=pd.to_numeric(data['votes'])
new_data = data[
    (data['genre'] == 'Drama') &
    (data['duration'] > 30) &
    (data['rating'] > 5) &
    (data['votes'] > 100000) &
    (data['votes'] < 200000)
]

In [63]:
new_data

,title,year,certificate,duration,genre,rating,description,stars,votes
682,Locke,(2013),R,85.0,Drama,7.1,"Ivan Locke, a dedicated family man and success...","['Steven Knight', '| ', ' Stars:', 'Tom Har...",150008.0
788,Roma,(2018),R,135.0,Drama,7.7,A year in the life of a middle-class family's ...,"['Alfonso Cuarón', '| ', ' Stars:', 'Yalitz...",157396.0